#!/usr/bin/env python3
"""Audit the retrieval corpus for id-shaped (vacuous) theorems.

A theorem is *id-shaped* when its conclusion appears verbatim as the type of
one of its hypotheses — the proof is literally `exact h`. Such "scalar
stand-in" lemmas verify nothing, rank highly in BM25 search (their names
describe a real mathematical fact), and dilute trust in what "in the
library" means.

This script only REPORTS — removal needs review (other modules may import
the declarations, and some restatements are deliberate interface shims).

Usage:
    python scripts/audit_corpus_vacuity.py [--corpus rlverify/corpus.jsonl]
                                           [--out rlverify/results/vacuity_audit.md]
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from rlverify.vacuity import _norm, split_top_level  # noqa: E402


def audit(corpus_path: Path) -> list[dict]:
    findings = []
    with open(corpus_path) as f:
        for line in f:
            entry = json.loads(line)
            stmt = entry.get("statement", "")
            parsed = split_top_level(stmt)
            if parsed is None:
                continue
            hyps, concl = parsed
            n_concl = _norm(concl)
            if not n_concl:
                continue
            for h in hyps:
                if _norm(h) == n_concl:
                    findings.append({
                        "id": entry["id"],
                        "source": f"{entry.get('source_file', '?')}:"
                                  f"{entry.get('source_line', '?')}",
                        "conclusion": n_concl,
                    })
                    break
    return findings


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--corpus", default=str(ROOT / "rlverify" / "corpus.jsonl"))
    ap.add_argument("--out", default=str(ROOT / "rlverify" / "results"
                                         / "vacuity_audit.md"))
    args = ap.parse_args()

    findings = audit(Path(args.corpus))
    lines = [
        "# Corpus vacuity audit — id-shaped theorems",
        "",
        "Theorems whose conclusion appears verbatim as a hypothesis type",
        "(the proof is `exact h`). These verify nothing and pollute search.",
        "Generated by `scripts/audit_corpus_vacuity.py`; REVIEW before",
        "removing — other modules may import them.",
        "",
        f"**{len(findings)} finding(s).**",
        "",
    ]
    for f in findings:
        lines += [f"- `{f['id']}`",
                  f"  - source: `{f['source']}`",
                  f"  - conclusion ≡ hypothesis: `{f['conclusion'][:100]}`"]
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines) + "\n")
    print(f"{len(findings)} id-shaped theorem(s) → {out}")
    for f in findings:
        print(f"  ✗ {f['id']}")


if __name__ == "__main__":
    main()
